export const icons = {
  // Brands
  Brands: [
    'fa-brands fa-500px',
    'fa-brands fa-amazon',
    'fa-brands fa-adn',
    'fa-brands fa-android',
    'fa-brands fa-angellist',
    'fa-brands fa-apple',
    'fa-brands fa-bandcamp',
    'fa-brands fa-behance',
    'fa-brands fa-behance-square',
    'fa-brands fa-bitbucket',
    // 'fa-brands fa-bitbucket-square',
    'fa-brands fa-bitcoin',
    'fa-brands fa-black-tie',
    'fa-brands fa-bluetooth',
    'fa-brands fa-bluetooth-b',
    'fa-brands fa-btc',
    'fa-brands fa-buysellads',
    'fa-brands fa-cc-amex',
    'fa-brands fa-cc-mastercard',
    'fa-brands fa-cc-paypal',
    'fa-brands fa-cc-stripe',
    'fa-brands fa-cc-visa',
    'fa-brands fa-chrome',
    'fa-brands fa-codepen',
    'fa-brands fa-codiepie',
    'fa-brands fa-connectdevelop',
    'fa-brands fa-contao',
    'fa-brands fa-css3',
    'fa-brands fa-dashcube',
    'fa-brands fa-delicious',
    'fa-brands fa-deviantart',
    'fa-brands fa-digg',
    'fa-brands fa-dribbble',
    'fa-brands fa-dropbox',
    'fa-brands fa-drupal',
    'fa-brands fa-edge',
    // 'fa-brands fa-eercast',
    'fa-brands fa-empire',
    'fa-brands fa-envira',
    'fa-brands fa-etsy',
    'fa-brands fa-expeditedssl',
    'fa-brands fa-facebook',
    'fa-brands fa-facebook-f',
    // 'fa-brands fa-facebook-official',
    'fa-brands fa-facebook-square',
    'fa-brands fa-firefox',
    'fa-brands fa-first-order',
    'fa-brands fa-flickr',
    'fa-brands fa-fonticons',
    'fa-brands fa-font-awesome',
    'fa-brands fa-fort-awesome',
    'fa-brands fa-forumbee',
    'fa-brands fa-foursquare',
    // 'fa-brands fa-ge',
    'fa-brands fa-get-pocket',
    'fa-brands fa-gg',
    'fa-brands fa-gg-circle',
    'fa-brands fa-git',
    'fa-brands fa-git-square',
    'fa-brands fa-github',
    'fa-brands fa-github-alt',
    'fa-brands fa-github-square',
    'fa-brands fa-gitlab',
    // 'fa-brands fa-gittip',
    'fa-brands fa-glide',
    'fa-brands fa-glide-g',
    'fa-brands fa-google',
    'fa-brands fa-google-plus',
    // 'fa-brands fa-google-plus-circle',
    // 'fa-brands fa-google-plus-official',
    'fa-brands fa-google-plus-square',
    'fa-brands fa-google-wallet',
    'fa-brands fa-gratipay',
    'fa-brands fa-grav',
    'fa-brands fa-hacker-news',
    'fa-brands fa-houzz',
    'fa-brands fa-html5',
    'fa-brands fa-imdb',
    'fa-brands fa-instagram',
    'fa-brands fa-internet-explorer',
    'fa-brands fa-ioxhost',
    'fa-brands fa-joomla',
    'fa-brands fa-jsfiddle',
    'fa-brands fa-lastfm',
    'fa-brands fa-lastfm-square',
    'fa-brands fa-leanpub',
    'fa-brands fa-linkedin',
    // 'fa-brands fa-linkedin-square',
    'fa-brands fa-linode',
    'fa-brands fa-linux',
    'fa-brands fa-maxcdn',
    // 'fa-brands fa-meanpath',
    'fa-brands fa-medium',
    'fa-brands fa-meetup',
    'fa-brands fa-mixcloud',
    'fa-brands fa-modx',
    'fa-brands fa-odnoklassniki',
    'fa-brands fa-odnoklassniki-square',
    'fa-brands fa-opencart',
    'fa-brands fa-openid',
    'fa-brands fa-opera',
    'fa-brands fa-optin-monster',
    'fa-brands fa-pagelines',
    'fa-brands fa-paypal',
    'fa-brands fa-pied-piper',
    'fa-brands fa-pied-piper-alt',
    'fa-brands fa-pinterest',
    'fa-brands fa-pinterest-p',
    'fa-brands fa-pinterest-square',
    'fa-brands fa-product-hunt',
    'fa-brands fa-qq',
    'fa-brands fa-quora',
    // 'fa-brands fa-ra',
    'fa-brands fa-ravelry',
    'fa-brands fa-rebel',
    'fa-brands fa-reddit',
    'fa-brands fa-reddit-alien',
    'fa-brands fa-reddit-square',
    'fa-brands fa-renren',
    'fa-brands fa-safari',
    'fa-brands fa-scribd',
    'fa-brands fa-sellsy',
    // 'fa-brands fa-share-alt',
    // 'fa-brands fa-share-alt-square',
    'fa-brands fa-shirtsinbulk',
    'fa-brands fa-snapchat',
    'fa-brands fa-snapchat-square',
    'fa-brands fa-simplybuilt',
    'fa-brands fa-skyatlas',
    'fa-brands fa-skype',
    'fa-brands fa-slack',
    'fa-brands fa-slideshare',
    'fa-brands fa-soundcloud',
    'fa-brands fa-spotify',
    'fa-brands fa-stack-exchange',
    'fa-brands fa-stack-overflow',
    'fa-brands fa-steam',
    'fa-brands fa-steam-square',
    'fa-brands fa-stumbleupon',
    'fa-brands fa-stumbleupon-circle',
    'fa-brands fa-superpowers',
    'fa-brands fa-telegram',
    'fa-brands fa-tencent-weibo',
    'fa-brands fa-themeisle',
    'fa-brands fa-trello',
    // 'fa-brands fa-tripadvisor',
    'fa-brands fa-tumblr',
    'fa-brands fa-tumblr-square',
    'fa-brands fa-twitch',
    'fa-brands fa-twitter',
    'fa-brands fa-twitter-square',
    'fa-brands fa-usb',
    'fa-brands fa-viacoin',
    'fa-brands fa-viadeo',
    'fa-brands fa-viadeo-square',
    'fa-brands fa-vimeo',
    'fa-brands fa-vimeo-square',
    'fa-brands fa-vine',
    'fa-brands fa-vk',
    // 'fa-brands fa-wechat',
    'fa-brands fa-weibo',
    'fa-brands fa-weixin',
    'fa-brands fa-whatsapp',
    'fa-brands fa-wikipedia-w',
    'fa-brands fa-windows',
    'fa-brands fa-wordpress',
    'fa-brands fa-wpbeginner',
    'fa-brands fa-wpexplorer',
    'fa-brands fa-wpforms',
    'fa-brands fa-xing',
    'fa-brands fa-xing-square',
    'fa-brands fa-y-combinator',
    'fa-brands fa-yahoo',
    'fa-brands fa-yelp',
    // 'fa-brands fa-yc',
    'fa-brands fa-yoast',
    'fa-brands fa-youtube',
    // 'fa-brands fa-youtube-play',
    'fa-brands fa-youtube-square',
  ],

  // Chart
  Chart: [
    'fa-chart-area',
    'fa-chart-bar',
    'fa-chart-line',
    'fa-chart-pie',
  ],

  // Currency
  Currency: [
    // 'fa-bitcoin',
    // 'fa-btc',
    'fa-cny',
    'fa-dollar-sign',
    'fa-euro-sign',
    'fa-gbp',
    'fa-ils',
    'fa-inr',
    'fa-jpy',
    'fa-krw',
    'fa-money-bill-wave',
    'fa-rmb',
    'fa-rouble',
    'fa-rub',
    'fa-ruble-sign',
    'fa-rupee-sign',
    'fa-shekel-sign',
    'fa-sheqel-sign',
    'fa-try',
    'fa-turkish-lira',
    'fa-usd',
    'fa-won',
    'fa-yen',
  ],

  // Directional
  Directional: [
    'fa-arrow-up-from-bracket',
    'fa-angle-double-down',
    'fa-angle-double-left',
    'fa-angle-double-right',
    'fa-angle-double-up',
    'fa-angle-down',
    'fa-angle-left',
    'fa-angle-right',
    'fa-angle-up',
    'fa-arrow-circle-down',
    'fa-arrow-circle-left',
    'fa-arrow-circle-right',
    'fa-arrow-circle-up',
    'fa-arrow-down',
    'fa-arrow-left',
    'fa-arrow-right',
    'fa-arrow-up',
    'fa-caret-down',
    'fa-caret-left',
    'fa-caret-right',
    'fa-caret-up',
    'fa-chevron-circle-down',
    'fa-chevron-circle-left',
    'fa-chevron-circle-right',
    'fa-chevron-circle-up',
    'fa-chevron-down',
    'fa-chevron-left',
    'fa-chevron-right',
    'fa-chevron-up',
    'fa-hand-point-down',
    'fa-hand-point-left',
    'fa-hand-point-right',
    'fa-hand-point-up',
    'fa-long-arrow-alt-down',
    'fa-long-arrow-alt-left',
    'fa-long-arrow-alt-right',
    'fa-long-arrow-alt-up',
    'fa-long-arrow-down',
    'fa-long-arrow-left',
    'fa-long-arrow-right',
    'fa-long-arrow-up',
    // 'fa-toggle-down',
    // 'fa-toggle-left',
    // 'fa-toggle-right',
    // 'fa-toggle-up',
  ],

  // Forms
  Forms: [
    'fa-check',
    'fa-check-circle',
    'fa-check-square',
    'fa-circle',
    'fa-circle-notch',
    'fa-dot-circle',
    'fa-edit',
    'fa-envelope',
    'fa-envelope-open',
    'fa-envelope-open-text',
    'fa-envelope-square',
    'fa-exclamation',
    'fa-exclamation-circle',
    'fa-exclamation-triangle',
    'fa-eye',
    'fa-eye-dropper',
    'fa-eye-slash',
    'fa-frown',
    'fa-frown-open',
    'fa-heart',
    'fa-heart-broken',
    'fa-id-badge',
    'fa-id-card',
    'fa-id-card-alt',
    'fa-info',
    'fa-info-circle',
    'fa-key',
    'fa-lightbulb',
    // 'fa-lightbulb-on',
    'fa-lock',
    'fa-lock-open',
    'fa-minus',
    'fa-minus-circle',
    'fa-minus-square',
    'fa-mobile',
    'fa-mobile-alt',
    'fa-moon',
    'fa-paperclip',
    'fa-question',
    'fa-question-circle',
    'fa-radiation',
    'fa-radiation-alt',
    'fa-receipt',
    'fa-sad-cry',
    'fa-sad-tear',
    'fa-smile',
    'fa-smile-beam',
    'fa-smile-wink',
    'fa-square',
    'fa-square-full',
    'fa-star',
    'fa-star-half',
    'fa-star-half-alt',
    'fa-star-of-david',
    'fa-star-of-life',
    'fa-sticky-note',
    'fa-sun',
    'fa-surprise',
    'fa-tachometer-alt',
    'fa-times',
    'fa-times-circle',
    'fa-tachometer-alt',
    'fa-thumbs-down',
    'fa-thumbs-up',
    'fa-toggle-off',
    'fa-toggle-on',
    'fa-trash',
    'fa-trash-alt',
    'fa-user',
    'fa-user-alt',
    'fa-user-cog',
    'fa-user-edit',
    'fa-user-friends',
    'fa-user-lock',
    'fa-user-md',
    'fa-user-plus',
    'fa-user-secret',
    'fa-user-times',
    'fa-users',
  ],

  // Media
  Media: [
    'fa-camera',
    'fa-camera-retro',
    'fa-file-audio',
    'fa-file-image',
    'fa-file-video',
    'fa-film',
    'fa-photo-video',
    'fa-play',
    'fa-play-circle',
    'fa-pause',
    'fa-stop',
    'fa-volume-down',
    'fa-volume-mute',
    'fa-volume-off',
    'fa-volume-up',
  ],

  // Medical
  Medical: [
    'fa-ambulance',
    'fa-bacterium',
    'fa-bed',
    'fa-biohazard',
    'fa-blind',
    'fa-bone',
    'fa-brain',
    'fa-burn',
    'fa-capsules',
    'fa-first-aid',
    'fa-flask',
    'fa-h-square',
    'fa-hospital',
    'fa-hospital-alt',
    'fa-hospital-symbol',
    'fa-hospital-user',
    // 'fa-inhaler',
    'fa-lungs',
    'fa-lungs-virus',
    'fa-notes-medical',
    'fa-pills',
    'fa-stethoscope',
    'fa-syringe',
    'fa-temperature-high',
    'fa-temperature-low',
    'fa-tooth',
    'fa-user-md',
    'fa-user-nurse',
  ],

  // Nature
  Nature: [
    'fa-tree',
    'fa-leaf',
    'fa-seedling',
    // 'fa-plant',
    'fa-campground',
    'fa-water',
    'fa-mountain',
    'fa-sun',
    'fa-cloud',
    'fa-cloud-sun',
    'fa-cloud-sun-rain',
    'fa-cloud-rain',
    'fa-cloud-showers-heavy',
    'fa-cloud-meatball',
    // 'fa-cloud-snow',
    'fa-cloud-moon',
    'fa-cloud-moon-rain',
    'fa-snowflake',
  ],

  // Objects
  Objects: [
    'fa-archive',
    // 'fa-bag',
    // 'fa-bag-check',
    'fa-bag-shopping',
    'fa-box',
    'fa-box-open',
    'fa-broom',
    'fa-calendar',
    'fa-calendar-check',
    'fa-calendar-day',
    'fa-calendar-minus',
    'fa-calendar-plus',
    'fa-calendar-week',
    'fa-calendar-alt',
    'fa-cash-register',
    'fa-certificate',
    'fa-clock',
    // 'fa-clock-eight',
    // 'fa-clock-nine',
    // 'fa-clock-ten',
    // 'fa-clothes',
    'fa-couch',
    'fa-drum',
    'fa-fan',
    'fa-gift',
    'fa-globe',
    'fa-globe-americas',
    'fa-globe-africa',
    'fa-globe-asia',
    'fa-guitar',
    'fa-hourglass',
    'fa-hourglass-half',
    'fa-keyboard',
    'fa-lightbulb',
    'fa-luggage-cart',
    'fa-microphone',
    // 'fa-mug',
    'fa-paint-brush',
    'fa-paint-roller',
    'fa-pen',
    'fa-phone',
    'fa-phone-alt',
    // 'fa-photo',
    'fa-robot',
    'fa-satellite',
    'fa-satellite-dish',
    // 'fa-scale',
    // 'fa-skateboard',
    'fa-sun',
    'fa-tablet',
    'fa-tachometer-alt',
    'fa-tachometer-alt-fast',
    // 'fa-tachometer-alt-fastest',
    'fa-tv',
    'fa-video',
    'fa-video-slash',
  ],

  // Social
  Social: [
    // 'fa-facebook',
    // 'fa-facebook-f',
    // 'fa-facebook-messenger',
    // 'fa-facebook-square',
    // 'fa-google',
    // 'fa-google-plus',
    // 'fa-google-plus-g',
    // 'fa-google-plus-square',
    // 'fa-linkedin',
    // 'fa-linkedin-in',
    // 'fa-twitter',
    // 'fa-twitter-square',
    // 'fa-youtube',
    // 'fa-youtube-square',
  ],

  // Text
  Text: [
    'fa-font',
    'fa-heading',
    'fa-bold',
    'fa-italic',
    'fa-underline',
    'fa-strikethrough',
    'fa-text-height',
    'fa-text-width',
    'fa-align-left',
    'fa-align-center',
    'fa-align-right',
    'fa-align-justify',
    'fa-list',
    'fa-list-ol',
    'fa-list-ul',
    'fa-list-alt',
    // 'fa-list-square',
    'fa-sort-alpha-down',
    'fa-sort-alpha-up',
    'fa-sort-numeric-down',
    'fa-sort-numeric-up',
    'fa-sort-amount-down',
    'fa-sort-amount-up',
  ],
};